// https://www.terraform.io/docs/providers/google/r/endpoints_service.html
// generated from terraform resource schema

import { Construct } from 'constructs';
import { TerraformResource } from 'cdktf';
import { TerraformMetaArguments } from 'cdktf';
import { ComplexComputedList } from "cdktf";

// Configuration

export interface EndpointsServiceConfig extends TerraformMetaArguments {
  /** The full text of the Service Config YAML file (Example located here). If provided, must also provide protoc_output_base64. open_api config must not be provided. */
  readonly grpcConfig?: string;
  /** The full text of the OpenAPI YAML configuration as described here. Either this, or both of grpc_config and protoc_output_base64 must be specified. */
  readonly openapiConfig?: string;
  /** The project ID that the service belongs to. If not provided, provider project is used. */
  readonly project?: string;
  /** The full contents of the Service Descriptor File generated by protoc. This should be a compiled .pb file, base64-encoded. */
  readonly protocOutputBase64?: string;
  /** The name of the service. Usually of the form $apiname.endpoints.$projectid.cloud.goog. */
  readonly serviceName: string;
  /** timeouts block */
  readonly timeouts?: EndpointsServiceTimeouts;
}
export class EndpointsServiceApisMethods extends ComplexComputedList {

  // name - computed: true, optional: false, required: true
  public get name() {
    return this.getStringAttribute('name');
  }

  // request_type - computed: true, optional: false, required: true
  public get requestType() {
    return this.getStringAttribute('request_type');
  }

  // response_type - computed: true, optional: false, required: true
  public get responseType() {
    return this.getStringAttribute('response_type');
  }

  // syntax - computed: true, optional: false, required: true
  public get syntax() {
    return this.getStringAttribute('syntax');
  }
}
export class EndpointsServiceApis extends ComplexComputedList {

  // methods - computed: true, optional: false, required: true
  public get methods() {
    return 'not implemented' as any;
  }

  // name - computed: true, optional: false, required: true
  public get name() {
    return this.getStringAttribute('name');
  }

  // syntax - computed: true, optional: false, required: true
  public get syntax() {
    return this.getStringAttribute('syntax');
  }

  // version - computed: true, optional: false, required: true
  public get version() {
    return this.getStringAttribute('version');
  }
}
export class EndpointsServiceEndpoints extends ComplexComputedList {

  // address - computed: true, optional: false, required: true
  public get address() {
    return this.getStringAttribute('address');
  }

  // name - computed: true, optional: false, required: true
  public get name() {
    return this.getStringAttribute('name');
  }
}
export interface EndpointsServiceTimeouts {
  readonly create?: string;
  readonly delete?: string;
  readonly update?: string;
}

// Resource

export class EndpointsService extends TerraformResource {

  // ===========
  // INITIALIZER
  // ===========

  public constructor(scope: Construct, id: string, config: EndpointsServiceConfig) {
    super(scope, id, {
      terraformResourceType: 'google_endpoints_service',
      terraformGeneratorMetadata: {
        providerName: 'google'
      },
      provider: config.provider,
      dependsOn: config.dependsOn,
      count: config.count,
      lifecycle: config.lifecycle
    });
    this._grpcConfig = config.grpcConfig;
    this._openapiConfig = config.openapiConfig;
    this._project = config.project;
    this._protocOutputBase64 = config.protocOutputBase64;
    this._serviceName = config.serviceName;
    this._timeouts = config.timeouts;
  }

  // ==========
  // ATTRIBUTES
  // ==========

  // apis - computed: true, optional: false, required: true
  public apis(index: string) {
    return new EndpointsServiceApis(this, 'apis', index);
  }

  // config_id - computed: true, optional: false, required: true
  public get configId() {
    return this.getStringAttribute('config_id');
  }

  // dns_address - computed: true, optional: false, required: true
  public get dnsAddress() {
    return this.getStringAttribute('dns_address');
  }

  // endpoints - computed: true, optional: false, required: true
  public endpoints(index: string) {
    return new EndpointsServiceEndpoints(this, 'endpoints', index);
  }

  // grpc_config - computed: false, optional: true, required: false
  private _grpcConfig?: string;
  public get grpcConfig() {
    return this._grpcConfig;
  }
  public set grpcConfig(value: string | undefined) {
    this._grpcConfig = value;
  }

  // id - computed: true, optional: true, required: false
  private _id?: string;
  public get id() {
    return this._id ?? this.getStringAttribute('id');
  }
  public set id(value: string | undefined) {
    this._id = value;
  }

  // openapi_config - computed: false, optional: true, required: false
  private _openapiConfig?: string;
  public get openapiConfig() {
    return this._openapiConfig;
  }
  public set openapiConfig(value: string | undefined) {
    this._openapiConfig = value;
  }

  // project - computed: true, optional: true, required: false
  private _project?: string;
  public get project() {
    return this._project ?? this.getStringAttribute('project');
  }
  public set project(value: string | undefined) {
    this._project = value;
  }

  // protoc_output_base64 - computed: false, optional: true, required: false
  private _protocOutputBase64?: string;
  public get protocOutputBase64() {
    return this._protocOutputBase64;
  }
  public set protocOutputBase64(value: string | undefined) {
    this._protocOutputBase64 = value;
  }

  // service_name - computed: false, optional: false, required: true
  private _serviceName: string;
  public get serviceName() {
    return this._serviceName;
  }
  public set serviceName(value: string) {
    this._serviceName = value;
  }

  // timeouts - computed: false, optional: true, required: false
  private _timeouts?: EndpointsServiceTimeouts;
  public get timeouts() {
    return this._timeouts;
  }
  public set timeouts(value: EndpointsServiceTimeouts | undefined) {
    this._timeouts = value;
  }

  // =========
  // SYNTHESIS
  // =========

  public synthesizeAttributes(): { [name: string]: any } {
    return {
      grpc_config: this._grpcConfig,
      openapi_config: this._openapiConfig,
      project: this._project,
      protoc_output_base64: this._protocOutputBase64,
      service_name: this._serviceName,
      timeouts: this._timeouts,
    };
  }
}
